### PR TITLE
Replace brotli sources with git submodule

### PR DESCRIPTION
**Pull request by eustas**
Replace brotli sources with git submodule for easier updates.

### CODE REVIEW

**Comment by matthewcheok** [comment]
Did you try compiling the framework? I'm getting build errors.
screen shot 2015-10-16 at 7 42 05 am

**Comment by matthewcheok** [comment]
One problem with submodules could be if the API surface changes, we could break immediately. Is it possible if we target specific release tags in their branch?

**Comment by eustas** [comment]
Sorry, hasn't checked that it compiles.

About API - no worries - it doesn't automatically pull the newest version, it sticks to the commit hash that is specified in submodule.

**Comment by eustas** [comment]
Now it compiles for OSX. Unfortunately can't check if it compiles for iOS =(

**Comment by matthewcheok** [comment]
Yes it does compile but the playground demo no longer works.

**Comment by matthewcheok** [comment]
FYI you can compile for iOS but maybe you can't test it on device if you don't have one - just change the scheme.

**Pull request closed without merging**
